Repository exasol/extension-manager, pull requests merged in 2022-06, with the labels that each got.

#18 17: Added check for preconditions of extensions
  .github/workflows/ci-build.yml
  .github/workflows/interface-ci-build.yml
  .golangci.yaml
  backend/extensionAPI/ExaAllScriptTable_test.go
  backend/extensionAPI/extensionApi.go
  backend/extensionAPI/extensionApi_test.go
  backend/extensionController/BucketFsApi.go
  backend/extensionController/BucketFsApi_test.go
  backend/extensionController/extensionController.go
  backend/extensionController/extensionController_test.go
  backend/go.mod
  backend/go.sum
  backend/integrationTesting/extensionForTesting/.gitignore
  backend/integrationTesting/extensionForTesting/extensionForTestingTemplate.ts
  backend/integrationTesting/extensionForTesting/package-lock.json
  backend/integrationTesting/extensionForTesting/package.json
  backend/integrationTesting/extensionForTestingFixture.go
  backend/integrationTesting/integrationSuite.go
  backend/integrationTesting/integrationTestSuite.go
  backend/integrationTesting/testExtensionBuilder.go
  backend/restAPI/restApi.go
  backend/restAPI/restApi_test.go
  doc/changes/changes_0.1.0.md
  doc/developers_guide/developers_guide.md
  interface/.gitignore
  interface/package.json
  interface/src/api.ts
  interface/tsconfig.json
Labels: feature

#21 Feature/20 swagger
  .github/workflows/ci-build.yml
  .gitignore
  README.md
  backend/generatedApiDocs/docs.go
  backend/generatedApiDocs/swagger.json
  backend/generatedApiDocs/swagger.yaml
  backend/go-generate.go
  backend/go.mod
  backend/go.sum
  backend/restAPI/restApi.go
  doc/changes/changes_0.1.0.md
  sonar-project.properties
Labels: documentation

#24 refactor/23: Moved go code from backend/ folder to project root
  .github/workflows/ci-build.yml
  ExasolSqlClient.go
  doc/changes/changes_0.1.0.md
  extensionAPI/ExaAllScriptTable.go
  extensionAPI/ExaAllScriptTable_test.go
  extensionAPI/extensionApi.go
  extensionAPI/extensionApi_test.go
  extensionController/BucketFsApi.go
  extensionController/BucketFsApi_test.go
  extensionController/ExtensionFinder.go
  extensionController/extensionController.go
  extensionController/extensionController_test.go
  generatedApiDocs/docs.go
  generatedApiDocs/swagger.json
  generatedApiDocs/swagger.yaml
  go-generate.go
  go.mod
  go.sum
  integrationTesting/extensionForTesting/.gitignore
  integrationTesting/extensionForTesting/extensionForTestingTemplate.ts
  integrationTesting/extensionForTesting/package.json
  integrationTesting/extensionForTesting/tsconfig.json
  integrationTesting/integrationTestSuite.go
  integrationTesting/luaScriptFixture.go
  integrationTesting/testExtensionBuilder.go
  main/main.go
  restAPI/restApi.go
  restAPI/restApi_test.go
  sonar-project.properties
Labels: refactoring

#25 feature/14: Added parameters to installations response
  doc/changes/changes_0.1.0.md
  doc/design/design.md
  extensionAPI/extensionApi.go
  extensionAPI/extensionApi_test.go
  extensionController/extensionController_test.go
  generatedApiDocs/docs.go
  generatedApiDocs/swagger.json
  generatedApiDocs/swagger.yaml
  integrationTesting/extensionForTesting/extensionForTestingTemplate.ts
  integrationTesting/extensionForTesting/package.json
  integrationTesting/testExtensionBuilder.go
  restAPI/restApi.go
  restAPI/restApi_test.go
Labels: feature

#32 feature/31: Added parameter validator
  doc/changes/changes_0.1.0.md
  go-generate.go
  parameterValidator/.gitignore
  parameterValidator/package-lock.json
  parameterValidator/package.json
  parameterValidator/parameterValidator.go
  parameterValidator/parameterValidatorWrapper.ts
  parameterValidator/parameterValidator_test.go
  parameterValidator/tsconfig.json
Labels: feature

#34 Update the design document
  doc/design/design.md
Labels: documentation
